name: Build Java App with Maven, Push Docker Image to JFrog, and Scan Code with SonarCloud

# Trigger workflow on push or pull request to the 'main' branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up JDK 17
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      # Step 3: Cache Maven dependencies
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Build the project using Maven
      - name: Build with Maven
        run: mvn clean install

      # Step 5: Determine Docker tag
      - name: Determine Docker Tag
        id: tag
        run: |
          if [[ "${{ github.ref_name }}" == "main" || "${{ github.ref_name }}" == "master" ]]; then
            echo "TAG=latest" >> $GITHUB_ENV
          else
            echo "TAG=${{ github.ref_name }}" >> $GITHUB_ENV
          fi

      # Step 6: Configure Docker for insecure registry
      - name: Configure Docker for insecure registry
        run: |
          echo '{ "insecure-registries": ["44.201.244.220:8081"] }' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker

      # Step 7: Build Docker image for Spring PetClinic
      - name: Build Docker image
        run: docker build -t spring-petclinic:${{ env.TAG }} .

      # Step 8: Tag the Docker image according to the official command
      - name: Tag Docker image
        run: docker tag spring-petclinic:${{ env.TAG }} 44.201.244.220:8081/docker-local-1/spring-petclinic:${{ env.TAG }}

      # Step 9: Log in to Docker using JFrog credentials
      - name: Log in to Docker
        run: echo "${{ secrets.JFROG_API_KEY }}" | docker login -u "${{ secrets.JFROG_USERNAME }}" --password-stdin http://44.201.244.220:8081

      # Step 10: Push Docker image to JFrog Artifactory Docker registry
      - name: Push Docker image to JFrog
        run: docker push 44.201.244.220:8081/docker-local-1/spring-petclinic:${{ env.TAG }}

      # Step 11: Run SonarCloud scan
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v1
        with:
          projectKey: victordgr8t  # SonarCloud project key
          organization: victormodebe  # Ensure this matches your SonarCloud organization key
          token: ${{ secrets.SONAR_TOKEN }}  # SonarCloud authentication token stored in secrets
